#
# Build stage
#
FROM maven:3.9.6-eclipse-temurin-17 AS build
ENV HOME=/usr/app
RUN mkdir -p $HOME
RUN mkdir -p /tmp/uploads
WORKDIR $HOME
ADD . $HOME
RUN mvn install
EXPOSE 8080
WORKDIR $HOME/quartz-manager-web-showcase
CMD ["mvn", "spring-boot:run"]

